# Generated by Django 4.0.5 on 2022-06-17 15:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_customersignup_ci_customersignup_nearest_bustop'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_loan', models.PositiveIntegerField(default=0)),
                ('payable_loan', models.PositiveIntegerField(default=0)),
                ('date_approved', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_user', to='account.customersignup')),
            ],
        ),
        migrations.CreateModel(
            name='loanCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(max_length=250)),
                ('date_approved', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_repayment', to='account.customersignup')),
                ('initialAmount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loanApp.customerloan')),
            ],
        ),
        migrations.CreateModel(
            name='loanTransaction',
            fields=[
                ('transaction', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment', models.PositiveIntegerField(default=0)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_customer', to='account.customersignup')),
            ],
        ),
        migrations.CreateModel(
            name='loanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('status_date', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('guarantor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guarantor_no', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('amount', models.PositiveIntegerField(default=1000)),
                ('days', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loanApp.loancategory')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_loan', to='account.customersignup')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=250)),
                ('account_no', models.CharField(blank=True, max_length=50, null=True)),
                ('nin', models.CharField(blank=True, max_length=50, null=True)),
                ('bvn', models.CharField(blank=True, max_length=50, null=True)),
                ('card_no', models.CharField(blank=True, max_length=50, null=True)),
                ('next_of_kin', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bank', to='account.customersignup')),
            ],
        ),
    ]
