# Generated by Django 4.0.2 on 2022-06-21 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_remove_customerdetail_state_and_more'),
        ('loanApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbank',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bank', to='account.customerinfo'),
        ),
        migrations.AlterField(
            model_name='customerloan',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_user', to='account.customerinfo'),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_loan', to='account.customerinfo'),
        ),
        migrations.AlterField(
            model_name='loantransaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_customer', to='account.customerinfo'),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_repayment', to='account.customerinfo'),
        ),
    ]
