# Generated by Django 4.0.2 on 2022-06-21 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_delete_customerdetail_delete_customerstate'),
        ('loanApp', '0002_alter_customerbank_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbank',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bank', to='account.customerinfo'),
        ),
    ]
