# Generated by Django 4.0.2 on 2022-06-21 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loanApp', '0003_alter_customerbank_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbank',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bank', to=settings.AUTH_USER_MODEL),
        ),
    ]
