# Generated by Django 4.0.2 on 2022-06-21 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loanApp', '0004_alter_customerbank_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbank',
            name='bank_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customerbank',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_bank', to=settings.AUTH_USER_MODEL),
        ),
    ]
