# Generated by Django 4.0.2 on 2022-06-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0005_alter_customerbank_bank_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerbank',
            old_name='customer',
            new_name='user',
        ),
    ]
