# Generated by Django 4.0.2 on 2022-06-21 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loanApp', '0006_rename_customer_customerbank_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbank',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_bank', to=settings.AUTH_USER_MODEL),
        ),
    ]
