# Generated by Django 4.0.2 on 2022-06-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0007_alter_customerbank_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbank',
            name='account_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerbank',
            name='bvn',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerbank',
            name='card_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerbank',
            name='nin',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
