# Generated by Django 4.0.2 on 2022-06-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0008_alter_customerbank_account_no_alter_customerbank_bvn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbank',
            name='account_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerbank',
            name='bvn',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerbank',
            name='card_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerbank',
            name='nin',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
