# Generated by Django 4.0.2 on 2022-06-26 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loanApp', '0010_alter_customerbank_account_no_alter_customerbank_bvn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_loan', to=settings.AUTH_USER_MODEL),
        ),
    ]
