# Generated by Django 4.0.2 on 2022-07-13 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loanApp', '0013_alter_loantransaction_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_loan', to=settings.AUTH_USER_MODEL),
        ),
    ]
