# Generated by Django 4.0.2 on 2022-07-14 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0018_alter_loantransaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='Loantransaction',
            name='amt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loanApp.customerloan'),
        ),
    ]
