# Generated by Django 4.0.2 on 2022-07-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0021_remove_loantransaction_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loantransaction',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='loantransaction',
            name='payment_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
