# Generated by Django 4.0.2 on 2022-07-14 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loanApp', '0022_remove_loantransaction_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantransaction',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
