# Generated by Django 4.0.2 on 2022-07-14 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loanApp', '0024_alter_customerbank_user_alter_customerloan_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantransaction',
            name='amt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loanApp.customerloan'),
        ),
        migrations.AddField(
            model_name='loantransaction',
            name='transaction',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='loantransaction',
            name='transaction_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36),
        ),
        migrations.AlterField(
            model_name='loantransaction',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
