# Generated by Django 4.0.2 on 2022-07-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0026_remove_loantransaction_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantransaction',
            name='amt',
            field=models.ManyToManyField(to='loanApp.CustomerLoan'),
        ),
    ]
