# Generated by Django 4.0.2 on 2022-07-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0027_loantransaction_amt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loantransaction',
            name='amt',
        ),
    ]
