# Generated by Django 4.0.2 on 2022-07-14 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0028_remove_loantransaction_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantransaction',
            name='amt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loanApp.customerloan'),
        ),
    ]
