# Generated by Django 4.0.2 on 2022-07-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0029_loantransaction_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerloan',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
