# Generated by Django 4.0.2 on 2022-07-14 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loanApp', '0030_customerloan_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerloan',
            name='price',
        ),
        migrations.CreateModel(
            name='CustomerLoanTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan', models.FloatField(default=0.0)),
                ('payable_amount', models.CharField(blank=True, max_length=20, null=True)),
                ('approved_date', models.DateField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
