# Generated by Django 4.0.2 on 2022-07-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0031_remove_customerloan_price_customerloantransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerloan',
            name='payable_loan',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customerloan',
            name='total_loan',
            field=models.IntegerField(default=0),
        ),
    ]
