# Generated by Django 4.0.2 on 2022-07-14 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0032_alter_customerloan_payable_loan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantransaction',
            name='am',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loanApp.customerloantransaction'),
        ),
    ]
