# Generated by Django 4.0.2 on 2022-07-14 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0034_transaction'),
    ]

    operations = [
        #migrations.AlterField(
         #   model_name='transaction',
          #  name='item',
           # field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loanApp.customerloan'),
        #),
    ]
