# Generated by Django 4.0.2 on 2022-07-14 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loanApp', '0037_transaction_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='payable_id',
            new_name='payment_id',
        ),
        migrations.RemoveField(
            model_name='customerloantransaction',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='customerloantransaction',
            name='payable_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='item',
        ),
        migrations.AlterField(
            model_name='customerloantransaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loanUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loanApp.customerloantransaction'),
        ),
    ]
