# Generated by Django 4.0.2 on 2022-07-14 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loanApp', '0041_remove_transaction_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loantransaction',
            name='amt',
        ),
        migrations.AlterField(
            model_name='customerloan',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loantransaction',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
