# Generated by Django 4.0.2 on 2022-07-15 06:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0044_alter_loanrequest_customer_alter_repayment_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantransaction',
            name='amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loanApp.loanrequest'),
        ),
        migrations.AddField(
            model_name='loantransaction',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loantransaction',
            name='transaction_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36),
        ),
    ]
