# Generated by Django 4.0.2 on 2022-07-15 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0051_remove_loantransaction_payment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loantransaction',
            old_name='transaction',
            new_name='transaction_id',
        ),
    ]
