# Generated by Django 4.0.2 on 2022-07-17 23:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import loanApp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loanApp', '0054_alter_loanrequest_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loantransaction',
            name='amount',
        ),
        migrations.AddField(
            model_name='customerloan',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 16, 23, 23, 35, 748915)),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('deadline', models.DateField(default=loanApp.models.get_deadline)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
