# Generated by Django 4.0.2 on 2022-07-18 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0056_alter_customerloan_mydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerloan',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 7, 27, 31, 149204)),
        ),
    ]
