# Generated by Django 4.0.2 on 2022-07-18 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0059_customerloan_mydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerloan',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 14, 41, 49, 932736)),
        ),
    ]
