# Generated by Django 4.0.2 on 2022-07-18 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0061_customerloan_bal_alter_customerloan_mydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerloan',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 14, 45, 12, 593529)),
        ),
    ]
