# Generated by Django 4.0.2 on 2022-07-19 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0062_alter_customerloan_mydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerloan',
            name='mydate',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2022, 7, 20, 5, 33, 59, 984805)),
        ),
    ]
