# Generated by Django 4.0.2 on 2022-07-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0064_alter_customerloan_mydate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mydate', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.AlterField(
            model_name='customerloan',
            name='mydate',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
