# Generated by Django 4.0.2 on 2022-07-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0065_mymodel_alter_customerloan_mydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerloan',
            name='mydate',
            field=models.DateTimeField(null=True),
        ),
    ]
