# Generated by Django 4.0.2 on 2022-07-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0067_remove_customerloan_mydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerloan',
            name='mydate',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
