# Generated by Django 4.0.2 on 2022-07-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0068_customerloan_mydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantransaction',
            name='totatl_payment',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
