# Generated by Django 4.0.2 on 2022-07-20 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0069_loantransaction_totatl_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loantransaction',
            old_name='totatl_payment',
            new_name='total_payment',
        ),
    ]
