# Generated by Django 4.0.2 on 2022-07-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0070_rename_totatl_payment_loantransaction_total_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loantransaction',
            options={'verbose_name_plural': 'loanTransaction'},
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='complete_payment',
            field=models.BooleanField(default=False),
        ),
    ]
