# Generated by Django 4.0.2 on 2022-07-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0071_alter_loantransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerloan',
            name='total_amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
