# Generated by Django 4.0.2 on 2022-07-23 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loanApp', '0074_rename_status_customerloan_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerloan',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
