# Generated by Django 4.0.2 on 2022-07-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0076_loanrequest_total_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repayment',
        ),
    ]
