# Generated by Django 4.0.2 on 2022-07-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0079_alter_customerloan_date_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='profit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
