# Generated by Django 4.0.2 on 2022-07-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0080_loanrequest_profit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerloan',
            old_name='bal',
            new_name='balance',
        ),
        migrations.AddField(
            model_name='customerloan',
            name='total_amount_paid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
