# Generated by Django 4.0.2 on 2022-07-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0081_rename_bal_customerloan_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerloan',
            name='bal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
