# Generated by Django 4.0.2 on 2022-08-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0082_customerloan_bal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerloan',
            name='payment',
            field=models.CharField(default='Not fully paid yet', max_length=20),
        ),
    ]
