# Generated by Django 4.0.2 on 2022-08-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0083_alter_customerloan_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerloan',
            name='payment',
            field=models.CharField(default='Not paid yet', max_length=20),
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
