# Generated by Django 4.0.2 on 2022-10-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0084_alter_customerloan_payment_delete_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loantransaction',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='loantransaction',
            name='transactionId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loantransaction',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
