# Generated by Django 4.0.5 on 2022-06-17 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersignup',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customersignup',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customersignup',
            name='last_name',
        ),
    ]
