# Generated by Django 4.0.5 on 2022-06-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_customersignup_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersignup',
            name='ci',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customersignup',
            name='nearest_bustop',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
