# Generated by Django 4.0.5 on 2022-06-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_city_customersignup_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersignup',
            old_name='ci',
            new_name='city',
        ),
    ]
