# Generated by Django 4.0.5 on 2022-06-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_ci_customersignup_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersignup',
            name='profile_picture',
            field=models.FileField(upload_to='profile_pic'),
        ),
    ]
