# Generated by Django 4.0.5 on 2022-06-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customersignup_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersignup',
            name='phone',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
