# Generated by Django 4.0.5 on 2022-06-19 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_customersignup_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersignup',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.customerstate'),
        ),
    ]
