# Generated by Django 4.0.5 on 2022-06-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_customersignup_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersignup',
            name='business_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customersignup',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_pic'),
        ),
    ]
