# Generated by Django 4.0.5 on 2022-06-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_customersignup_business_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersignup',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
