# Generated by Django 4.0.5 on 2022-06-19 09:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_customersignup_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersignup',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
