# Generated by Django 4.0.5 on 2022-06-19 14:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0011_alter_customersignup_profile_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerSignUp',
            new_name='CustomerDetail',
        ),
        migrations.AlterModelOptions(
            name='customerdetail',
            options={'verbose_name_plural': 'CustomerDetail'},
        ),
    ]
