# Generated by Django 4.0.5 on 2022-06-19 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0012_rename_customersignup_customerdetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
