# Generated by Django 4.0.2 on 2022-06-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_customerdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstate',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
