# Generated by Django 4.0.2 on 2022-06-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_customerstate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('dept', models.CharField(max_length=50, null=True)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=11, null=True)),
            ],
        ),
    ]
