# Generated by Django 4.0.2 on 2022-06-21 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_state_alter_customerdetail_user_student_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='account.state'),
        ),
    ]
