# Generated by Django 4.0.2 on 2022-06-21 06:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_student_user_alter_student_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
