# Generated by Django 4.0.2 on 2022-06-21 07:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0022_student_profile_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='CustomerInfo',
        ),
    ]
