# Generated by Django 4.0.2 on 2022-06-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_rename_student_customerinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='business',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='dateRegistered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='nearest_bustop',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
