# Generated by Django 4.0.2 on 2022-06-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_customerinfo_address_customerinfo_business_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='name',
        ),
    ]
