# Generated by Django 4.0.2 on 2022-06-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_remove_customerinfo_age_remove_customerinfo_dept_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetail',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customerdetail',
            name='user',
        ),
    ]
