# Generated by Django 4.0.2 on 2022-07-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='city',
        ),
    ]
