# Generated by Django 4.0.2 on 2022-07-23 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_remove_customerinfo_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='location',
        ),
    ]
