# Generated by Django 4.0.2 on 2022-07-23 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_remove_customerinfo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.location'),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.state'),
        ),
    ]
